# Generated by Django 6.0 on 2026-01-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_academicresult_id_alter_careergoal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='KUCCPS Institution Code', max_length=50, unique=True)),
                ('institution_type', models.CharField(choices=[('PUBLIC_UNIVERSITY', 'Public University'), ('PRIVATE_UNIVERSITY', 'Private University'), ('TVET', 'TVET/College')], default='PUBLIC_UNIVERSITY', max_length=20)),
                ('location', models.CharField(help_text='City or Town', max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma/Level 6'), ('CERTIFICATE', 'Certificate/Level 5'), ('ARTISAN', 'Artisan/Level 4')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kuccps_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('job_market_demand', models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='MODERATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.clustergroup')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='universities.programmelevel')),
            ],
        ),
        migrations.AddField(
            model_name='clustergroup',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='universities.programmelevel'),
        ),
        migrations.CreateModel(
            name='ProgrammeOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='universities.institution')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='universities.programme')),
            ],
            options={
                'unique_together': {('programme', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='ProgrammeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_category', models.CharField(blank=True, choices=[('GP1', 'Group 1 (Compulsory)'), ('GP2', 'Group 2 (Sciences)'), ('GP3', 'Group 3 (Humanities)'), ('GP4', 'Group 4 (Technicals)'), ('GP5', 'Group 5 (Foreign Languages/Business)')], help_text='If no specific subject, require a category (e.g. Any Group 2)', max_length=3, null=True)),
                ('minimum_grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-')], default='C+', max_length=2)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='universities.programme')),
                ('subject', models.ForeignKey(blank=True, help_text='Specific subject required (e.g. Math)', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CutOffPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('weighted_cluster_points', models.DecimalField(decimal_places=3, max_digits=6)),
                ('placed_students', models.IntegerField(blank=True, null=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='universities.programmeoffering')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('offering', 'year')},
            },
        ),
    ]
