# Generated by Django 6.0 on 2026-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoffpoint',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Declared slots for this offering', null=True),
        ),
        migrations.AddField(
            model_name='cutoffpoint',
            name='cutoff_type',
            field=models.CharField(choices=[('WEIGHTED_POINTS', 'Weighted Cluster Points'), ('MEAN_GRADE', 'Mean Grade')], default='WEIGHTED_POINTS', help_text='Whether this uses weighted points or mean grade', max_length=20),
        ),
        migrations.AddField(
            model_name='cutoffpoint',
            name='mean_grade_cutoff',
            field=models.CharField(blank=True, help_text='Cut-off for TVET programmes (e.g., C-, C+)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cutoffpoint',
            name='placed_students',
            field=models.IntegerField(blank=True, help_text='Number of students placed', null=True),
        ),
        migrations.AlterField(
            model_name='cutoffpoint',
            name='weighted_cluster_points',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cut-off for degree programmes (e.g., 42.155)', max_digits=6, null=True),
        ),
    ]
