# Generated by Django 6.0 on 2026-01-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_cutoffpoint_capacity_cutoffpoint_cutoff_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='created_at',
        ),
        migrations.AddField(
            model_name='programme',
            name='minimum_mean_grade',
            field=models.CharField(blank=True, help_text='Minimum mean grade for TVET programmes (e.g., C-, D+, C)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='programmerequirement',
            name='description',
            field=models.TextField(blank=True, help_text="Full requirement text for complex rules (e.g., 'ENG(101)/KIS(102):C+' or 'Any two Group II subjects')"),
        ),
        migrations.AddField(
            model_name='programmerequirement',
            name='is_category',
            field=models.BooleanField(default=False, help_text="True if requiring 'Any Group 2' or alternatives like 'ENG or KIS'"),
        ),
        migrations.AlterField(
            model_name='programme',
            name='kuccps_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='universities.programmelevel'),
        ),
    ]
