# Generated by Django 6.0 on 2026-01-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_remove_programme_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustergroup',
            name='subject_1',
            field=models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clustergroup',
            name='subject_2',
            field=models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clustergroup',
            name='subject_3',
            field=models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clustergroup',
            name='subject_4',
            field=models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SubClusterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., '1A', '2A', '2B', '2C'", max_length=10, unique=True)),
                ('subject_1', models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True)),
                ('subject_2', models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True)),
                ('subject_3', models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True)),
                ('subject_4', models.CharField(blank=True, help_text="e.g., 'ENG C+', 'MATH B'", max_length=100, null=True)),
                ('cluster', models.ForeignKey(help_text='Parent cluster this subcluster belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subclusters', to='universities.clustergroup')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='sub_cluster',
            field=models.ForeignKey(blank=True, help_text='Optional: specific subcluster within the cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='universities.subclustergroup'),
        ),
    ]
