# Generated by Django 6.0 on 2026-02-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_clustergroup_subject_1_clustergroup_subject_2_and_more'),
    ]

    operations = [
        # Add index on CutOffPoint.year for faster year filtering
        migrations.AddIndex(
            model_name='cutoffpoint',
            index=models.Index(fields=['year'], name='cutoff_year_idx'),
        ),
        # Add index on CutOffPoint.weighted_cluster_points for faster filtering
        migrations.AddIndex(
            model_name='cutoffpoint',
            index=models.Index(fields=['weighted_cluster_points'], name='cutoff_points_idx'),
        ),
        # Add index on Programme.sub_cluster for faster lookups
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['sub_cluster'], name='prog_subcluster_idx'),
        ),
        # Add index on ProgrammeOffering.programme for faster joins
        migrations.AddIndex(
            model_name='programmeoffering',
            index=models.Index(fields=['programme'], name='offering_prog_idx'),
        ),
    ]
