# Generated by Django 6.0.2 on 2026-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cutoffpoint',
            name='cutoff_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='cutoffpoint',
            name='cutoff_points_idx',
        ),
        migrations.RemoveIndex(
            model_name='programme',
            name='prog_subcluster_idx',
        ),
        migrations.RemoveIndex(
            model_name='programmeoffering',
            name='offering_prog_idx',
        ),
        migrations.AlterField(
            model_name='programmerequirement',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('GP1', 'Group 1 (Compulsory)'), ('GP2', 'Group 2 (Sciences)'), ('GP3', 'Group 3 (Humanities)'), ('GP4', 'Group 4 (Technicals)'), ('GP5', 'Group 5 (Foreign Languages/Business)'), ('GPX', 'Other / Custom')], help_text='If no specific subject, require a category (e.g. Any Group 2)', max_length=3, null=True),
        ),
    ]
