# Generated by Django 6.0 on 2026-03-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_remove_cutoffpoint_cutoff_year_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('node_type', models.CharField(choices=[('SUBJECT_AREA', 'Subject Area'), ('SKILL', 'Skill'), ('CAREER_OUTCOME', 'Career Outcome')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='programmeoffering',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual tuition/programme cost in KES', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('PREREQUISITE', 'Prerequisite For'), ('LEADS_TO', 'Leads To'), ('COMPONENT_OF', 'Component Of'), ('RELATED_TO', 'Related To')], max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='universities.knowledgenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='universities.knowledgenode')),
            ],
            options={
                'unique_together': {('source', 'target', 'link_type')},
            },
        ),
        migrations.CreateModel(
            name='ProgrammeOutcomeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.ForeignKey(limit_choices_to={'node_type': 'CAREER_OUTCOME'}, on_delete=django.db.models.deletion.CASCADE, to='universities.knowledgenode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_mappings', to='universities.programme')),
            ],
            options={
                'unique_together': {('programme', 'outcome')},
            },
        ),
    ]
