# Generated by Django 6.0 on 2026-02-18 14:37

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prompt_period_start',
            field=models.DateField(default=apps.users.models.get_first_day_of_month),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prompts_used_in_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('mentor_elite', 'Mentor Elite'), ('scholar_vvip', 'Scholar VVIP')], db_index=True, default='explorer', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_tier', models.CharField(choices=[('explorer', 'Explorer'), ('mentor_elite', 'Mentor Elite'), ('scholar_vvip', 'Scholar VVIP')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(help_text='e.g. mpesa', max_length=50)),
                ('reference', models.CharField(help_text='M-Pesa CheckoutRequestID or Receipt number', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, help_text='Raw callback payload from provider for auditing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
