# Generated by Django 5.2.10 on 2026-03-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_prompt_period_start_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionTransaction',
        ),
    ]
