# Generated by Django 6.0 on 2026-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_tier',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('mentor_elite', 'Mentor Elite'), ('scholar_vvip', 'Scholar VVIP')], default='mentor_elite', max_length=50),
        ),
    ]
