# Generated by Django 6.0 on 2026-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_transaction_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
