import React from "react";
import "./LegalLayout.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const TermsOfService = () => {
    return (
        <div className="legal-page">
            <Navbar />
            <div className="legal-container">
                <section className="legal-hero-section">
                    <header className="legal-header">
                        <h1>Terms of Service</h1>
                        <p className="last-updated">Last updated: 28 January 2026</p>
                    </header>
                </section>

                <div className="legal-content">
                    <section>
                        <h2>1. Acceptance of Terms</h2>
                        <p>
                            By accesssing or using the <strong>KeDira</strong> platform, you agree to be bound by these Terms of Service.
                            If you do not agree, please do not use the service.
                        </p>
                    </section>

                    <section>
                        <h2>2. Description of Service</h2>
                        <p>
                            KeDira is an AI-driven course recommender designed to help students identify potential
                            academic paths based on their KCSE results and interests. This version specifically supports
                            the Kenyan <strong>8-4-4</strong> (and transitioning) educational system.
                        </p>
                    </section>

                    <section className="legal-contact-box">
                        <h2>3. Advisory Only - No Guarantees</h2>
                        <p>
                            <strong>Important:</strong> Recommendations generated by KeDira are for informational and advisory purposes only.
                            They do <strong>not</strong> constitute a guarantee of:
                        </p>
                        <ul>
                            <li>Official KUCCPS placement or admission.</li>
                            <li>Admission to any specific university or college.</li>
                            <li>Employment outcomes or career success.</li>
                        </ul>
                        <p>
                            Final placement decisions are made solely by KUCCPS and individual institutions. We encourage you to
                            verify all recommendations against official KUCCPS guidelines.
                        </p>
                    </section>

                    <section>
                        <h2>4. User Responsibilities</h2>
                        <p>As a user, you agree to:</p>
                        <ul>
                            <li>Provide accurate academic and personal information.</li>
                            <li>Use the tool as a guide to complement your own research.</li>
                            <li>Not attempt to manipulate, reverse-engineer, or misuse the AI recommendation logic.</li>
                            <li>Be responsible for maintaining the security of your account.</li>
                        </ul>
                    </section>

                    <section>
                        <h2>5. Subscriptions & Payments</h2>
                        <p>Our service operates on a three-tiered subscription model:</p>
                        <ul>
                            <li><strong>Explorer (Free):</strong> Includes 1 free prompt. Each prompt provides your top 3 personalized course recommendations.</li>
                            <li><strong>Mentor Elite (KES 199/month):</strong> Includes 5 prompts. Each prompt provides your top 5 personalized course recommendations with deeper analytical insights.</li>
                            <li><strong>Scholar VVIP (KES 499/month):</strong> Provides unlimited prompts. Each prompt showcases your top 10 recommended courses with comprehensive lifecycle analysis and action plans.</li>
                            <li>Accounts will automatically downgrade to the Explorer tier after premium expiry unless renewed.</li>
                        </ul>
                    </section>

                    <section>
                        <h2>6. Intellectual Property</h2>
                        <p>
                            The KeDira platform, including its AI models, UI design, and content, belongs to <strong>PROACTED</strong>.
                            You retain ownership of the academic and personal inputs you provide.
                        </p>
                    </section>

                    <section>
                        <h2>7. Service Availability</h2>
                        <p>
                            We strive for constant availability, but the service may be temporarily unavailable for maintenance or updates.
                            PROACTED is not liable for any downtime or service interruptions.
                        </p>
                    </section>

                    <section>
                        <h2>8. Limitation of Liability</h2>
                        <p>
                            PROACTED shall not be liable for any decisions made based on our recommendations. You assume full
                            responsibility for your academic and career choices.
                        </p>
                    </section>

                    <section>
                        <h2>9. Governing Law</h2>
                        <p>
                            These terms are governed by and construed in accordance with the laws of the <strong>Republic of Kenya</strong>.
                            Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the Kenyan courts.
                        </p>
                    </section>

                    <section>
                        <h2>10. Contact</h2>
                        <p>For questions regarding these terms, please reach out to our support team.</p>
                        <a
                            href="https://wa.me/254743720033?text=Hello%20Career%20Compass%20Support,%20I%20have%20a%20question%20about%20the%20Terms%20of%20Service."
                            className="whatsapp-link"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            <span>Contact via WhatsApp Support</span>
                        </a>
                    </section>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default TermsOfService;
