import { useEffect, useCallback, useRef } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useNavigate } from 'react-router-dom';

const IDLE_TIMEOUT = 30 * 60 * 1000; // 30 minutes

const IdleLogout = () => {
    const { logout, user } = useAuth();
    const navigate = useNavigate();
    const timeoutRef = useRef(null);

    const handleLogout = useCallback(async () => {
        if (!user) return;
        console.log('Session expired due to inactivity. Logging out...');
        try {
            await logout();
            navigate('/signin', { state: { message: 'Your session has expired due to inactivity.' } });
        } catch (error) {
            console.error('Inactivity logout error:', error);
        }
    }, [logout, user, navigate]);

    const resetTimer = useCallback((event) => {
        // Task 1: Check if the activity is human (not bot activity)
        // event.isTrusted is true if the event was generated by a user action
        if (event && !event.isTrusted) return;

        if (timeoutRef.current) {
            clearTimeout(timeoutRef.current);
        }
        timeoutRef.current = setTimeout(handleLogout, IDLE_TIMEOUT);
    }, [handleLogout]);

    useEffect(() => {
        if (!user) return;

        const events = ['mousedown', 'mousemove', 'keypress', 'scroll', 'touchstart', 'click'];

        // Initialize timer
        resetTimer();

        events.forEach(event => {
            window.addEventListener(event, resetTimer);
        });

        return () => {
            if (timeoutRef.current) {
                clearTimeout(timeoutRef.current);
            }
            events.forEach(event => {
                window.removeEventListener(event, resetTimer);
            });
        };
    }, [user, resetTimer]);

    return null; // This component doesn't render anything
};

export default IdleLogout;
