"""
Django settings for course_recomeder_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

#====================================================================================#
#                                                                                    #
#       THIS IS THE 'psql' CODE I USED TO CREATE MY DATABASES                        #
#                                                                                    #
#====================================================================================#
#************************************************************************************#
# CREATE DATABASE ai_course_recommeder;                                              #   
# CREATE USER proacted_admin WITH PASSWORD 'ProActEd2026';                           #
# ALTER ROLE proacted_admin SET client_encoding TO 'utf8';                           #   
# ALTER ROLE proacted_admin SET default_transaction_isolation TO 'read committed';   #
# ALTER ROLE proacted_admin SET timezone TO 'UTC';                                   #   
# GRANT ALL PRIVILEGES ON DATABASE ai_course_recommeder TO proacted_admin;     #
# \q                                                                                 #   
#************************************************************************************#
#====================================================================================#
#                                                                                    #
#       THIS IS THE 'psql' CODE I USED TO GRANT MY USER PERMISIONS                   #
#                                                                                    #
#====================================================================================#
#************************************************************************************#
#-- Connect to your databases                                                        #
# \c ai_course_recommeder                                                            #           
# -- Grant schema permissions                                                        #       
# GRANT ALL PRIVILEGES ON SCHEMA public TO proacted_admin;                           #           
# -- Grant table creation permissions                                                #   
# GRANT CREATE ON DATABASE ai_course_recommeder TO proacted_admin;                   #
# -- Make sure the user owns the schema                                              #
# ALTER SCHEMA public OWNER TO proacted_admin;                                       #
#                                                                                    #
#************************************************************************************#
#====================================================================================#
#                                                                                    #
#       SUPERUSER CREDENTIALS I RECOMMEND USING                                      #
#                                                                                    #
#====================================================================================#
#************************************************************************************#
# Username: ProActEd                                                                 #   
# Email address: proacted641@gmail.com                                               #
# Password: ProActEd                                                                 #     
#************************************************************************************#
#====================================================================================#

import sys
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file - Force override to prevent system environment pollution
load_dotenv(BASE_DIR / '.env', override=True)
sys.path.append(str(BASE_DIR / 'apps'))
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Import Redis configuration utilities for graceful fallback
from utils.redis_config import is_redis_available, get_cache_backend, get_channel_layers

# Detect Redis availability (will print status message to console)
REDIS_AVAILABLE = is_redis_available()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# ============================================================================
# SECURITY LOCKDOWN: Production Headers
# ============================================================================
X_FRAME_OPTIONS = 'DENY'  # Prevents clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevents MIME sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enables browser XSS filter

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')
AUTH_USER_MODEL = 'users.CustomUser'

# Application definition
INSTALLED_APPS = [
    # Conditionally add Daphne (ASGI server) if Redis is available
    *(['daphne'] if REDIS_AVAILABLE else []),
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'csp',
    'subscriptions',

    'apps.users.apps.UsersConfig', 
    'apps.students.apps.StudentsConfig',
    'apps.universities.apps.UniversitiesConfig',
    'proacted_recommender_engine.apps.ProactedRecommenderEngineConfig',
    
    # Conditionally add Channels (WebSocket support) if Redis is available
    *(['channels'] if REDIS_AVAILABLE else []),
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'course_recomeder_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Conditionally use ASGI or WSGI based on Redis availability
if REDIS_AVAILABLE:
    ASGI_APPLICATION = 'course_recomeder_backend.asgi.application'
    print("✅ Running in ASGI mode with WebSocket support", file=sys.stderr)
else:
    WSGI_APPLICATION = 'course_recomeder_backend.wsgi.application'
    print("⚠️  Running in WSGI mode (no WebSocket support)", file=sys.stderr)




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.auth.supabase.SupabaseJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', 
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AIACADEMIA – PROACTED API Docs',
    'DESCRIPTION': 'Detailed API documentation for the AI Course Recommender system. All protected endpoints require a Supabase JWT Bearer Token.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{"bearerAuth": []}],
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "Enter your Supabase Access Token (JWT) to authorize requests."
            }
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    # Branding
    'SWAGGER_UI_DIST': 'SIDECAR', # Fallback
    'SWAGGER_UI_FAVICON_HREF': '/static/drf_spectacular/logo.png',
    
    'ENUM_NAME_OVERRIDES': {
        'CategoryEnum': 'students.models.Subject.CATEGORY_CHOICES',
    },
}

# Database - Supabase PostgreSQL with Connection Pooler (Supavisor)
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Project Reference: zuoujlipkmoqxrwcrdij
# Using connection pooler for IPv4 support

import dj_database_url

db_url = os.environ.get('DATABASE_URL')
if db_url:
    DATABASES = {
        'default': dj_database_url.parse(db_url, conn_max_age=600)
    }
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}
else:
    # Fallback to hardcoded pooler connection
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',
            'USER': 'postgres.zuoujlipkmoqxrwcrdij',
            'PASSWORD': 'ProActEd2026',
            'HOST': 'aws-1-eu-west-1.pooler.supabase.com',
            'PORT': '6543',
            'POOL_MODE': 'session',
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# STATIC_ROOT = BASE_DIR / "staticfiles" 


# ============================================================================
# CACHING CONFIGURATION - Auto-detection
# ============================================================================

CACHES = get_cache_backend()

if REDIS_AVAILABLE:
    print("✅ Redis caching enabled", file=sys.stderr)
else:
    print("⚠️  Using in-memory caching (no persistence)", file=sys.stderr)

# Cache timeout configurations
CACHE_TTL = {
    'SUBJECTS': 60 * 60 * 24,      # 24 hours (rarely changes)
    'INSTITUTIONS': 60 * 60 * 12,   # 12 hours
    'CLUSTERS': 60 * 60 * 24,       # 24 hours
    'PROGRAMMES': 60 * 60 * 2,      # 2 hours (more dynamic)
    'SEARCH_RESULTS': 60 * 5,       # 5 minutes (search queries)
}


# ============================================================================
# DJANGO CHANNELS CONFIGURATION - WebSockets (if Redis available)
# ============================================================================

if REDIS_AVAILABLE:
    CHANNEL_LAYERS = get_channel_layers()
    print("✅ WebSocket support enabled", file=sys.stderr)
else:
    # No channel layers if Redis unavailable
    print("⚠️  WebSocket disabled (Redis required)", file=sys.stderr)


# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

from utils.logging_config import setup_logging

LOGGING = setup_logging()


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Login lasts 1 hour before refresh needed
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.environ.get('SUPABASE_JWT_SECRET'),
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# ============================================================================
# CONTENT SECURITY POLICY (CSP)
# ============================================================================
# Policy: Default to 'self', allow inline styles/scripts for Admin/Swagger compatibility.
# Block everything else (external scripts, frames, objects).

# django-csp >= 4.0 format (replaces flat CSP_* variables)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'style-src': ("'self'", "'unsafe-inline'"),
        'script-src': ("'self'", "'unsafe-inline'"),
        'img-src': ("'self'", "data:"),
        'font-src': ("'self'", "data:"),
        'frame-ancestors': ("'self'",),  # Prevent Clickjacking
        'object-src': ("'none'",),
        'base-uri': ("'self'",),
        'form-action': ("'self'",),
        # Uncomment to allow Supabase connections from backend-served pages:
        # 'connect-src': ("'self'", "https://*.supabase.co"),
    }
}


# ============================================================================
# COOKIE SECURITY
# ============================================================================
# Protects the 'sessionid' and 'csrftoken' cookies used by Django Admin.
# Note: Your API uses JWT (Headers), so it is not affected by these settings.

# 1. HttpOnly: Prevents JavaScript from reading the session cookie (Critical for XSS protection)
SESSION_COOKIE_HTTPONLY = True
# CSRF cookie usually needs to be readable by JS for some frontend frameworks, 
# but since we use JWT for API, we can lock it down or leave default.
CSRF_COOKIE_HTTPONLY = False 

# 2. SameSite: Prevents the cookie from being sent in cross-site requests (CSRF protection)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# 3. Secure: Only send cookies over HTTPS.
# We connect this to DEBUG so it doesn't break your Localhost (HTTP) development.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    print("🔒 Production Security: Secure Cookies Enabled (HTTPS only)", file=sys.stderr)
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ============================================================================
# PAYHERO (env only)
# ============================================================================
PAYHERO_CHANNEL_ID = os.environ.get('PAYHERO_CHANNEL_ID', '')
PAYHERO_API_USERNAME = os.environ.get('PAYHERO_API_USERNAME', '')
PAYHERO_API_PASSWORD = os.environ.get('PAYHERO_API_PASSWORD', '')
PAYHERO_CALLBACK_URL = os.environ.get('PAYHERO_CALLBACK_URL', '')
PAYHERO_CALLBACK_SECRET = os.environ.get('PAYHERO_CALLBACK_SECRET', '')
