# Generated by Django 5.2.8 on 2025-12-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], max_length=2)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('SKILL', 'Skill'), ('INTEREST', 'Interest'), ('HOBBY', 'Hobby'), ('STYLE', 'Learning Style'), ('VALUE', 'Core Value')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=5, help_text='1-10 scale of how important this is to the student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcse_index_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('kcse_year', models.IntegerField(help_text='Year the student sat for KCSE')),
                ('mean_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(choices=[('GP1', 'Group 1 (Compulsory)'), ('GP2', 'Group 2 (Sciences)'), ('GP3', 'Group 3 (Humanities)'), ('GP4', 'Group 4 (Technicals)'), ('GP5', 'Group 5 (Foreign Languages/Business)')], max_length=3)),
            ],
        ),
    ]
