# Generated by Django 4.2.27 on 2026-01-26 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_academicresult_id_alter_careergoal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='The full multi-step wizard data.')),
                ('result', models.JSONField(help_text='The generated AI recommendation JSON.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
