# Generated by Django 4.2.27 on 2026-01-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_promptsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='budget_kes_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='constraints_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='exposure_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='long_term_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='self_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='short_term_goals',
            field=models.JSONField(blank=True, help_text='List of short term goals', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='time_hours_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_from_prompt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattribute',
            name='attribute_type',
            field=models.CharField(choices=[('SKILL', 'Skill'), ('INTEREST', 'Interest'), ('HOBBY', 'Hobby'), ('STYLE', 'Learning Style'), ('VALUE', 'Core Value'), ('SKILL_TECH', 'Technical Skill'), ('SKILL_SOFT', 'Soft Skill'), ('STRENGTH', 'Strength'), ('WEAKNESS', 'Weakness')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('GP1', 'Group 1 (Compulsory)'), ('GP2', 'Group 2 (Sciences)'), ('GP3', 'Group 3 (Humanities)'), ('GP4', 'Group 4 (Technicals)'), ('GP5', 'Group 5 (Foreign Languages/Business)'), ('GPX', 'Other / Custom')], max_length=3),
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_type', models.CharField(choices=[('parent', 'Parent/Guardian'), ('teacher', 'Teacher/Mentor'), ('friend', 'Friend/Peer'), ('other', 'Other')], max_length=20)),
                ('direction_field', models.CharField(help_text='Where they are directing the student (e.g. Medicine)', max_length=120)),
                ('general_path', models.CharField(choices=[('university', 'University'), ('tvet', 'TVET / College'), ('employment', 'Employment'), ('business', 'Business / Entrepreneurship')], max_length=20)),
                ('strength', models.PositiveSmallIntegerField(default=1, help_text='1-4 scale')),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('student_alignment', models.CharField(choices=[('agree', 'Agree'), ('partially_agree', 'Partially Agree'), ('neutral', 'Neutral'), ('disagree_but_complying', 'Disagree but Complying')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influences', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('weight', models.PositiveSmallIntegerField(default=50, help_text='0-100 importance')),
                ('order_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_priorities', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'key')},
            },
        ),
    ]
