# Generated by Django 4.2.27 on 2026-01-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_budget_kes_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='kcse_year',
            field=models.IntegerField(blank=True, help_text='Year the student sat for KCSE', null=True),
        ),
    ]
