# Generated by Django 6.0.2 on 2026-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='kcse_points',
            field=models.FloatField(blank=True, help_text='Total cluster points', null=True),
        ),
    ]
