# Generated by Django 6.0 on 2026-03-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentprofile_kcse_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsubmission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
